target 'Ridesharer' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps' # add this to use maps


  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # removed 'BatchedBridge' from array above because: https://github.com/facebook/react-native/releases/tag/v0.54.0

  pod 'react-native-maps', path: rn_maps_path

  pod 'GoogleMaps'  # add this to use maps
  pod 'react-native-google-maps', path: rn_maps_path  # add this to use maps

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end